version: '2'
services:
  # Gateway
  db_old:
    image: postgres
    ports:
      - "9000:5432"
  api:
    build: ./piflab-store-api-go
    image: zealotnt/piflab-store-api-go
    command: bash api-go-entry.sh postgres
    ports:
      - "9900:80"
    depends_on:
      - db_old
    links:
      - db_old
      - products
      - orders
    volumes:
      - ./piflab-store-api-go:/go/src/github.com/o0khoiclub0o/piflab-store-api-go
    env_file: ./piflab-store-api-go/.env

  # Products service
  db_product:
    image: postgres
    ports:
      - "9001:5432"
  products:
    build: ./piflab-products-service-api
    image: zealotnt/piflab-products-service-api
    command: bash api-go-entry.sh postgres
    ports:
      - "9901:9901"
    depends_on:
      - db_product
    links:
      - db_product
    volumes:
      - ./piflab-products-service-api:/go/src/github.com/o0khoiclub0o/piflab-store-api-go
    env_file: ./piflab-products-service-api/.env

  # Orders service
  db_order:
    image: postgres
    ports:
      - "9002:5432"
  orders:
    build: ./piflab-orders-service-api
    image: zealotnt/piflab-orders-service-api
    command: bash api-go-entry.sh postgres
    ports:
      - "9902:9902"
    depends_on:
      - db_order
    links:
      - db_order
    volumes:
      - ./piflab-orders-service-api:/go/src/github.com/o0khoiclub0o/piflab-store-api-go
    env_file: ./piflab-orders-service-api/.env
